USE [master]
GO

/****** Object:  Database [Meli]    Script Date: 28/05/2022 11:19:51 p. m. ******/
CREATE DATABASE [Meli]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Meli', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\Meli.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Meli_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\Meli_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Meli].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Meli] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Meli] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Meli] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Meli] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Meli] SET ARITHABORT OFF 
GO

ALTER DATABASE [Meli] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Meli] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Meli] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Meli] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Meli] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Meli] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Meli] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Meli] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Meli] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Meli] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Meli] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Meli] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Meli] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Meli] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Meli] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Meli] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Meli] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Meli] SET RECOVERY FULL 
GO

ALTER DATABASE [Meli] SET  MULTI_USER 
GO

ALTER DATABASE [Meli] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Meli] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Meli] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Meli] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Meli] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Meli] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Meli] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Meli] SET  READ_WRITE 
GO


